on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
jobs:
  test:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:     
    - name: Setup Meson
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: BSFishy/meson-build@v1
      with:
        action: test
