on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
jobs:
  test:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:     
    - name: Setup python
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: ashutoshvarma/setup-ninja@v1.1
    
    - name: setup meson
      run: pip3 install meson
    - run: meson setup build
    - run: meson wrap install jsoncpp
    - run: meson compile -C build
