on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - uses: threeal/cmake-action@v1.1.0
      with: 
        build-dir: build
