on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4.5.0
    - uses: ashutoshvarma/setup-ninja@v1.1
      with: 
        version: 1.10.0

    
    - name: setup meson
      run: |
        meson setup build
        meson wrap install jsoncpp
        meson compile -C build
